// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * T​i​t​l​e
	 */
	Title: string
	/**
	 * A​r​t​i​s​t
	 */
	Artist: string
	/**
	 * D​u​r​a​t​i​o​n
	 */
	Duration: string
	/**
	 * L​a​b​e​l
	 */
	Label: string
}

export type TranslationFunctions = {
	/**
	 * Title
	 */
	Title: () => LocalizedString
	/**
	 * Artist
	 */
	Artist: () => LocalizedString
	/**
	 * Duration
	 */
	Duration: () => LocalizedString
	/**
	 * Label
	 */
	Label: () => LocalizedString
}

export type Formatters = {}
